package com.developerputra.prihasi;


import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class Database2 extends SQLiteOpenHelper {
    private static final String DATABASE_NAME = "sistempakar";

    public Database2(Context context) {
        super(context, DATABASE_NAME, null, 1);
    }



    public void createTable(SQLiteDatabase db) {
        db.execSQL("DROP TABLE IF EXISTS gejala");
        db.execSQL("CREATE TABLE if not exists gejala (id TEXT PRIMARY KEY, nama TEXT, " +
                "ya VARCHAR(5), tidak VARCHAR(5), mulai VARCHAR(5), selesai VARCHAR(5));");
    }


    public void createTable3(SQLiteDatabase db3) {
        db3.execSQL("DROP TABLE IF EXISTS learning");
        db3.execSQL("CREATE TABLE if not exists learning (kode_learning TEXT PRIMARY KEY , " +
                "nama_learning TEXT, deskripsi TEXT, gambar TEXT);");
    }

    public void createTable4(SQLiteDatabase db4) {
        db4.execSQL("DROP TABLE IF EXISTS merawat");
        db4.execSQL("CREATE TABLE if not exists merawat (kode_merawat TEXT PRIMARY KEY , " +
                "nama_merawat TEXT, deskripsi_merawat TEXT, referensi_merawat TEXT);");
    }

    public void createTable5(SQLiteDatabase db5) {
        db5.execSQL("DROP TABLE IF EXISTS bayi");
        db5.execSQL("CREATE TABLE if not exists bayi (kode_merawat TEXT PRIMARY KEY , " +
                "nama_merawat TEXT, deskripsi_merawat TEXT, referensi_merawat TEXT);");
    }

    public void createTable6(SQLiteDatabase db6) {
        db6.execSQL("DROP TABLE IF EXISTS melahirkan");
        db6.execSQL("CREATE TABLE if not exists melahirkan (kode_merawat TEXT PRIMARY KEY , " +
                "nama_merawat TEXT, deskripsi_merawat TEXT, referensi_merawat TEXT);");
    }

    public void createTable7(SQLiteDatabase db7) {
        db7.execSQL("DROP TABLE IF EXISTS ibu");
        db7.execSQL("CREATE TABLE if not exists ibu (kode_ibu TEXT PRIMARY KEY , " +
                "nama_penyakit_ibu TEXT, deskripsi_penyakit_ibu TEXT, referensi_penyakit_ibu TEXT);");
    }



    public void generateData(SQLiteDatabase db) {
        ContentValues cv = new ContentValues();
        db.execSQL("INSERT INTO gejala VALUES ('G001','demam', 'G002', 'G016', 'Y', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G002','timbul ruam (bintik merah) yang menjalar ke seluruh tubuh', 'G003', 'G004_b', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G003','Sakit tenggorokan', 'G004_a', 'G004', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G004_a','Batuk', 'G005', 'G005', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G004','batuk', 'G005', 'G006', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G004_b','batuk', 'G005_b', 'G005_d', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G004_c','batuk', 'G005_b', 'G005_b', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G005','mata meradang', 'P001', 'P001', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G005_b','sakit tenggorokan', 'G006_c', 'G015_c', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G005_c','sakit tenggorokan', 'G022', 'G022', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G005_d','sakit tenggorokan', 'G015', 'G006_b', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G006','sakit kepala', 'G007', 'G007', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G006_b','Sakit kepala', 'G011', 'G011', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G006_c','Sakit kepala', 'G015', 'G015', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G007','sakit pada berbagai bagian tubuh', 'G008', 'G008', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G008','menggigil', 'G009', 'G009', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G009','anoreksia (gangguan psikologi takut memiliki kenaikan berat badan)', 'G010', 'G010', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G010','malaise (merasa tidak enak badan', 'P002', 'P002', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G011','mual dan muntah', 'G012', 'G012', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G012','mialgia (badan terasa pegal-pegal)', 'G013', 'G013', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G013','altralgia (nyeri pada sendi)', 'G014', 'G014', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G014','fotofobia (rasa takut abnormal pada cahaya)', 'P003', 'P003', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G015','hidung tersumbat', 'P004', 'P004', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G015_b','hidung tersumbat', 'G018_b', 'G018_b', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G015_c','hidung tersumbat', 'G018_c', 'G018_c', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G016','tubuh lemah', 'G017', 'G029', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G017','tidak nafsu makan', 'G018', 'G020', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G018','kondisi lelah', 'G019', 'G019', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G018_b','kondisi lelah', 'G025', 'G025', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G018_c','kondisi lelah', 'G028', 'G028', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G019','pucat dalam kelopak mata', 'P005', 'P005', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G020','kondisi sering buang air besar, biasanya lebih dari 4 kali sehari', 'G021', 'G021', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G021','kondisi nafas sering berhenti sejenak', 'P006', 'P006', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G022','kondisi sulit bernafas dan menelan', 'G023', 'G023', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G023','radang lidah disertai rasa sakit', 'G024', 'G024', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G024','kondisi darah dan lendir dalam kotoran', 'P007', 'P007', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G025','batuk-batuk disertai lendir berwarna kuning keabu-abuan atau hijau', 'G026', 'G026', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G026','sesak Nafas', 'G027', 'G027', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G027','kondisi sakit atau tidak nyaman pada dada', 'P008', 'P008', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G028','batuk terus menerus', 'P009', 'P009', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G029','kondisi mata terasa kasar dan gatal', 'G030', 'G005_c', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G030','mata merah dan berair', 'G031', 'G031', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('G031','kelopak mata merekat sewaktu bangun tidur', 'P010', 'P010', 'T', 'T');");
        db.execSQL("INSERT INTO gejala VALUES ('P001','CAMPAK', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P002','DEMAM DENGUE', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P003','DEMAM CHIKUNGUNYA', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P004','INFLUENZA', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P005','ANEMIA', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P006','DIARE', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P007','DIFTERI', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P008','BRONKITIS', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P009','BATUK REJAN (PERTUSIS)', '0', '0', 'T', 'Y');");
        db.execSQL("INSERT INTO gejala VALUES ('P010','KONJUNGTIVITIS', '0', '0', 'T', 'Y');");

    }


    public void generateData3(SQLiteDatabase db3) {
        db3.execSQL("INSERT INTO learning VALUES ('L001', 'BULAN 1',"+"'Sel telur yang telah dibuahi menjadi sekumpulan sel berbentuk bola yang menempel di dinding rahim. Kumpulan sel itu lalu berkembang bentuknya menjadi seperti udang sebesar beras. Di tahap ini tumbuh susunan saraf pusat dan jantung pada calon bayi.\n' , 'Buku Kebidanan' );");
        db3.execSQL("INSERT INTO learning VALUES ('L002', 'BULAN 2', "+"'- Umur kehamilan 6 minggu : terbentuknya tangan, kaki, otak dan organ-organ penting seperti jantung, hati, ginjal dan limpa.\n" +
                "- Umur kehamilan 7 minggu : terbentuknya otak dan mata.\n"+
                "- Umur kehamilan 8 minggu : terbentuknya struktur telinga, mata dan mulut.\n"+
                "- Umur kehamilan 10 minggu : jantung mulai berfungsi, terbentuknya paru-paru.\n', 'Buku Kebidanan' );");
        db3.execSQL("INSERT INTO learning VALUES ('L003', 'BULAN 3',"+"'Panjang embrio mencapai 5 cm dari kepala sampai pantat dan beratnya 14 gram (± sebesar sebutir telur ayam kampung). Wajah mulai terbentuk, hidung dan dagu bisa terlihat, kelopak mata bisa dibuka dan tertutup, bibir mulai mengisap-isap, kaki dan tangan sudah besar dan kecil, kuku jari-jari tangan terbentuk dengan baik, mulai menggengam jari-jarinya, alat kelamin mulai tampak, air kencing mulai di produksi.\n', 'Buku Kebidanan' );");
        db3.execSQL("INSERT INTO learning VALUES ('L004', 'BULAN 4', "+"'Bayi berkembang cepat, organ dalam terbentuk. Kuku jari tangan dan kaki bertumbuh. Dia tampak kurus karena belum ada lapisan lemak di dalam tubuhnya. Di akhir bulan rambut halus tumbuh di seluruh tubuh bayi.\n','Buku Kebidanan');");
        db3.execSQL("INSERT INTO learning VALUES ('L005', 'BULAN 5',"+"'Bayi berkembang makin pesat. Panjangnya kini mencapai 13 cm. Ia kini memproduksi selaput putih yang melapisi tubuhnya dan melindungi kulitnya. Rambut, alis dan bulu matanya tumbuh, indranya pun berkembang. Meski matanya terpejam, bayi dapat menangkap cahaya yang terang.\n', 'Buku Kebidanan' );");
        db3.execSQL("INSERT INTO learning VALUES ('L006', 'BULAN 6',"+"'Sistem pencernaan dan kekebalan tubuh semakin matang. Bayi mulai mengeluarkan air seni tanda sistem pencernaan mulai bekerja. Ia kini sudah bisa mengontrol gerak tubuhnya dan anda bisa merasakannya bergerak, khususnya saat anda istirahat. Gerakan anda dan suara ramai bikin ia tidur.\n', 'Buku Kebidanan' );");
        db3.execSQL("INSERT INTO learning VALUES ('L007', 'BULAN 7',"+"'Otak berkembang dengan cepat, panjang janin 35–38 cm, berat 1250 gram, dan janin bisa membuka dan menutup mata. 96% dari semua janin telah berganti posisi, yaitu posisi kepala di bawah, organ-organ tubuh mulai sempurna. Berat janin bertambah dengan cepat (janin mulai melatih gerkan-gerakan bernafas, mengontrol suhu badan dan lain-lain). Bayi yang lahir pada masa ini memerlukan perawatan yang khusus di unit perawatan intensif untuk bertahan hidup kandungan.\n','Buku Kebidanan');");
        db3.execSQL("INSERT INTO learning VALUES ('L008', 'BULAN 8',"+"'Gerakan bayi anda semakin terkordinasi, dan ia sudah bisa membuka dan menutup mata, juga merasakan rasa manis dan asam. Kepala bayi anda mungkin ada di bawah, di posisi siap dilahirkan. Tapi posisi ini bisa berubah sewaktu-waktu.\n','Buku Kebidanan');");
        db3.execSQL("INSERT INTO learning VALUES ('L009', 'BULAN 9',"+"'Bayi lengkap terbentuk dan ia kini bisa lahir kapan saja. Setiap minggu ia akan bertambah 225 gram. Lapisan lemak yang tebal mulai berkembang di bawah kulitnya, membuatnya tampak lebih berisi, dan memberi cadangan energi untuk digunakan pada saat ia keluar dari rahim.\n','Buku Kebidanan');");

    }

    public void generateData4(SQLiteDatabase db4) {
        db4.execSQL("INSERT INTO merawat VALUES ('R001', 'Melakukan pemeriksaan kehamilan rutin atau antenatal care (ANC)',"+"'Antenatal Care (ANC) adalah pemeriksaan kehamilan untuk mengoptimalkan kesehatan mental dan fisik ibu hamil. Ini bertujuan agar ibu hamil mampu menghadapi persalinan, masa nifas, pemberian ASI eksklusif, dan mengembalikan kesehatan reproduksinya dengan baik.\n\nPemeriksaan ini dapat berupa pemeriksaan fisik, pemeriksaan darah, dan USG untuk mengetahui masalah yang dapat muncul selama kehamilan. Anda dapat mendiskusikan berbagai hal seputar kehamilan Anda kepada bidan atau dokter, termasuk cara menjaga kehamilan, rencana melahirkan, atau segala kekhawatiran yang memenuhi kepala Anda. Biasanya, pemeriksaan ini harus dilakukan setiap bulan tapi tanyakan lagi pada dokter Anda kapan jadwal yang tepat untuk melakukan semua tes tersebut.\n\nKonsultasikan juga bila Anda memiliki masalah diabetes atau tiroid yang mungkin akan memengaruhi kehamilan Anda beserta cara mengatasinya. Dengan begitu, Anda dapat menjalani kehamilan dengan lebih aman dan lancar.\n' , 'Buku Kebidanan' );");
        db4.execSQL("INSERT INTO merawat VALUES ('R002', 'Minum suplemen khusus', "+"'Ketika memasuki masa kehamilan, maka kebutuhan gizi ibu meningkat. Banyak ibu yang tidak bisa memenuhi kebutuhan gizinya dengan baik, sehingga terancam kekurangan vitamin dan mineral. Tentunya akan memengaruhi kesehatan janin maupun ibu.\n\nMaka itu ibu hamil, apalagi yang hamil di usia 40 tahun, memerlukan suplemen khusus agar kebutuhan gizinya tercukupi dengan baik. Suplemen tambahan yang diberikan yaitu yang mengandung asam folat, zat besi, dan kalsium. Suplemen ini bermanfaat untuk mencegah beberapa cacat lahir terkait dengan sumsum tulang belakang dan otak, salah satunya spina bifida.\n\nBila Anda mengidap penyakit tertentu dan mengonsumsi obat-obatan, baiknya konsultasikan dulu pada dokter apakah Anda boleh lanjut minum obat tersebut atau tidak. Sebab, tidak semua obat dapat dikonsumsi oleh wanita yang sedang hamil.\n','Buku Kebidanan' );");
        db4.execSQL("INSERT INTO merawat VALUES ('R003', 'Istirahat yang cukup',"+"'Menurut Barbara O’Brien, M.D., seorang spesialis perinatal genetik di Women and Infants’ Hospital of Rhode Island, wanita yang hamil di usia 40 tahun harus lebih peka terhadap tubuhnya. Seperti dilansir dari Fit Pregnancy, wanita usia 40 tahun justru lebih bersemangat dalam beraktivitas, sehingga mereka cenderung ingin terus melakukan semua halnya sendiri.\n\nMaka, Anda perlu mengistirahatkan tubuh Anda sesering mungkin dan tidak memaksakan diri. Simpan tenaga Anda dengan istirahat yang cukup untuk menjaga kehamilan Anda di usia yang tak lagi muda.\n', 'Buku Kebidanan' );");
        db4.execSQL("INSERT INTO merawat VALUES ('R004', 'Makan makanan yang bergizi', "+"'Selama hamil, makanan dan nutrisi harus terjaga dengan baik. Asupan makanan yang tidak tepat dapat membuat gizi ibu hamil tidak tercukupi dan nantinya bisa berdampak pada kesehatan janin.\n\nOleh karena itu, penuhi asupan nutrisi Anda dengan makan makanan yang bergizi, terutama yang mengandung tinggi asam folat seperti sayuran hijau, jeruk, sereal, atau produk makanan lain yang telah diperkaya mineral ini. Banyaklah mengonsumsi sayur dan buah untuk menjaga kebutuhan serat harian dan hindari makanan cepat saji untuk sementara waktu.\n\nBila Anda penyuka makanan laut atau seafood, baiknya Anda lebih berhati-hati. Sebab, beberapa makanan laut mengandung merkuri yang dapat menyebabkan bayi cacat lahir, misalnya ikan hiu, king makerel, atau ikan todak. Makanan laut yang diperbolehkan untuk ibu hamil di antaranya salmon, udang, dan tuna. Namun, konsultasikan dulu pada dokter agar Anda tidak salah langkah.\n','Buku Kebidanan');");
        db4.execSQL("INSERT INTO merawat VALUES ('R005', 'Kendalikan berat badan',"+"'Beberapa dokter menganjurkan ibu hamil untuk menaikkan berat badannya hingga beberapa kilogram selama kehamilan. Anjuran ini tentunya disesuaikan dengan kondisi kesehatan ibu dan janin agar tidak meningkatkan risiko komplikasi kehamilan. Karena itu, konsultasikan pada dokter mengenai angka berat badan yang disarankan sesuai dengan kondisi Anda.\n', 'Buku Kebidanan' );");
        db4.execSQL("INSERT INTO merawat VALUES ('R006', 'Hindari pola hidup tak sehat',"+"'Sudah menjadi kewajiban para ibu hamil untuk menjaga pola hidup yang sehat, terutama Anda yang menjalani kehamilan di usia yang berisiko tinggi. Hindari berbagai pola hidup tak sehat seperti kebiasaan merokok dan minum alkohol, termasuk juga suami dan keluarga Anda.\n\nMeskipun Anda tidak merokok tetapi suami atau anggota keluarga lainnya merokok, ini tetap saja membuat Anda menjadi perokok pasif yang dapat membahayakan kesehatan Anda dan bayi. Jadi, mintalah suami Anda berhenti merokok, atau setidaknya tidak merokok di sekitar Anda.\n', 'Buku Kebidanan' );");
        db4.execSQL("INSERT INTO merawat VALUES ('R007', 'Melakukan vaksin',"+"'Idealnya, vaksinasi harus didapatkan sebelum Anda mulai merencanakan kehamilan. Pasalnya, kondisi hamil membuat sistem kekebalan tubuh cenderung menurun sehingga rentan terkena berbagai penyakit menular. Nah, di sinilah peran penting imunisasi saat hamil untuk meningkatkan kekebalan tubuh dan menjaga kesehatan bayi Anda kelak.\n\nNamun bila Anda terlambat mendapatkan vaksin sebelum hamil, Anda bisa melakukan vaksinasi saat hamil. Hal ini sudah terbukti aman bagi tumbuh kembang bayi dalam kandungan Anda. Vaksin yang aman untuk ibu hamil di antaranya hepatitis B, flu, dan tetanus diphteria pertusis (Tdap). Segera konsultasikan pada dokter untuk mendapatkan vaksin yang sesuai.\n','Buku Kebidanan');");

           }

    public void generateData5(SQLiteDatabase db5) {
        db5.execSQL("INSERT INTO bayi VALUES ('A001', 'Tali Pusat',"+"'Perawatan tali pusat harus hati-hati, karena mudah terkena infeksi. Jika tali pusat terkena air saat bayi dimandikan, keringkan dengan cotton buds atau kasa steril.\n\nJangan bubuhi ramuan apa pun pada pangkal tali pusat. Biasanya, tali pusat akan putus antara 1-2 minggu setelah kelahiran, tapi bisa juga lebih cepat atau lambat.\n\nSetelah tali pusat putus, jika kotor bersihkan dengan baby oil dengan lembut dan hati-hati.\n' , 'Buku Kebidanan' );");
        db5.execSQL("INSERT INTO bayi VALUES ('A002', 'Mata Bayi', "+"'Untuk membersihkan kotoran di mata, basuh dengan menggunakan kapas steril yang dibasahi air matang. Selalu gunakan satu kapas steril untuk tiap mata. Usap dengan arah dari dalam ke luar.\n','Buku Kebidanan' );");
        db5.execSQL("INSERT INTO bayi VALUES ('A003', 'Kulit',"+"'Bayi baru lahir minimal dimandikan sehari sekali karena ia belum tahan dingin. Entah dengan cara berendam di bak mandi atau dilap dengan waslap basah yang sudah diberi sabun bayi.\n\nUntuk mencegah munculnya biang keringat, atur temperatur ruangan/kamar bayi senyaman mungkin. Jangan sampai bayi kepanasan. Sirkulasi udara dalam kamar harus baik.\n', 'Buku Kebidanan' );");
        db5.execSQL("INSERT INTO bayi VALUES ('A004', 'Kulit Kepala', "+"'Kerak kulit atau cradle crap sering muncul di kulit kepala bayi. Hal ini disebabkan kulit kepala terkena debu, keringat dan polusi udara. Kerak kulit dapat dibersihkan menggunakan baby oil.\n\nCaranya, diamkan baby oil di atas kerak kulit kira-kira sekitar 10-15 menit, lalu bersihkan dengan kapas atau cotton bud secara lembut, dilanjutkan dengan pencucian.\n\nLakukan dengan lembut, di daerah ini terdapat satu peredaran darah di kepala yang menyambung dengan otak.\n\nUsahakan kulit kepala tetap sejuk dan kering, karena kerak ini akan makin parah jika kulit kepala berkeringat.\n','Buku Kebidanan');");
        db5.execSQL("INSERT INTO bayi VALUES ('A005', 'Rambut',"+"'Cuci rambut bayi menggunakan shampo khusus bayi dua kali seminggu. Basahi rambutnya dengan semprotan halus atau basuh dengan tangan.\n\nTambahkan satu-dua tetes sampo dan gosok lembut sampai berbusa. Jangan sampai shampo mengenai mata. Basuh sampai bersih dengan tangan.\n', 'Buku Kebidanan' );");
        db5.execSQL("INSERT INTO bayi VALUES ('A006', 'Hidung',"+"'Bagian dalam hidung punya daya pembersih sendiri dan tak perlu perawatan khusus. Jika ada cairan atau kotoran yang kelihatan keluar, bersihkan bagian luar hidung saja.\n\nJika bayi punya banyak lendir karena pilek dan mengganggu pernapasan, sedot keluar dengan cara dengan aspirator hidung bayi yang bersih. Tutup sebelah lubang hidung dengan jari, lalu isap sebelahnya. Lakukan secara bergantian.\n', 'Buku Kebidanan' );");
        db5.execSQL("INSERT INTO bayi VALUES ('A007', 'Telinga',"+"'Banyak ibu baru bingung dengan cara merawat bayi baru lahir yang satu ini. Seperti hidung, bagian dalam telinga juga tak boleh dibersihkan. Bunda boleh membersihkan jika kotoran itu sudah mencapai “pintu” keluar atau setelah melewati “tikungan” di dalam liang telinga luar.\n\nAda pendapat bahwa cotton buds justru membuat kotoran masuk ke dalam liang telinga. Cara yang disarankan adalah meneteskan 1 tetes baby oil ke liang telinga, dan kotoran akan keluar dengan sendirinya beberapa hari kemudian. Tak percaya bukan? Yuk kita coba.\n\nSementara daun telinga dapat dibersihkan tiap kali memandikan bayi. Gunakan cotton buds atau kapas yang dibasahi air hangat. Lakukan secara lembut.\n','Buku Kebidanan');");
        db5.execSQL("INSERT INTO bayi VALUES ('A008', 'Mulut',"+"'Mulut bayi tak perlu perawatan khusus. Jika lidah putih karena endapan susu formula, bisa dibersihkan dengan kasa steril yang dibahasi dengan air matang\n\nJaga kebersihan tangan Bunda, karena pada beberapa kasus ditemui jamur candida muncul di mulut bayi. Jika hal ini terjadi segera berobatlah ke dokter.\n','Buku Kebidanan');");
        db5.execSQL("INSERT INTO bayi VALUES ('A009', 'Kuku',"+"'Kuku sebaiknya dijaga kebersihannya dengan memotongnyanya secara berkala. Lakukan secara hati-hati, jangan sampai kulitnya ikut tergunting. Gunakan gunting kuku khusus bayi.\n\nUntuk mencegah kuku-kuku bayi menggores bagian-bagian yang membahayakan, tutuplah dengan sarung tangan saat bayi sedang tak diawasi.\n\nSelama ia dalam pengawasan, tangannya tak usah diberi sarung. Sebab, tangan merupakan bagian dari pancaindera yang harus dikembangkan.\n','Buku Kebidanan');");
        db5.execSQL("INSERT INTO bayi VALUES ('A010', 'Pantat Bayi',"+"'Pantat adalah daerah yang sensitif dengan bahan kimia deterjen, diapers dan kotoran sisa air kencing/tinja. Bila tidak bersih, sering kali timbul gatal-gatal dan merah di sekitar bokong.\n\nUntuk mencegahnya usahakan pantat dalam kondisi kering dan bersih. Sebaiknya gunakan diaper cream setelah pantat benar-benar kering, baru kemudian pakaikan diaper atau popok.\n\nJika sudah terlanjur timbul iritasi, cara alami yang dapat dilakukan adalah membiarkan pantat terbuka saat berjemur di pagi hari dengan terkena sinar matahari pagi. Tengkurapkan bayi di pangkuan Bunda.\n\nJika dalam 1-2 hari tidak membaik bahkan lecet atau berbintil-bintil kecil, hubungi dokter anak Anda.\n','Buku Kebidanan');");

    }

    public void generateData6(SQLiteDatabase db6) {
        db6.execSQL("INSERT INTO melahirkan VALUES ('B001', 'Persiapkan Tubuh Anda Menjelang Persalinan',"+"'melahirkan merupakan suatu hal yang harus Anda persiapkan dari jauh hari. Mulai dari persiapan fisik sampai persiapan mental. Untuk mempersiapkan tubuh Anda, Anda mungkin perlu untuk melakukan olahraga secara rutin.\n\nSelain untuk menjaga kebugaran tubuh Anda, olahraga juga dapat melancarkan sirkulasi darah Anda. Hal ini kemudian dapat membantu Anda meningkatkan elastisitas kulit. Olahraga kegel atau latihan dasar panggul juga dapat memperkuat otot-otot dasar panggul Anda, sehingga membantu Anda selama proses persalinan.\n\nSelain olahraga, Anda juga perlu mengonsumsi makanan sehat untuk memastikan kebutuhan nutrisi Anda terpenuhi dengan baik. Nutrisi dan hidrasi yang baik dapat mendukung kesehatan kulit dan otot Anda. Hal ini dapat mendukung peregangan otot perineum selama melahirkan dan pemulihan tubuh setelah melahirkan. Beberapa nutrisi penting yang baik Anda penuhi adalah lemak baik (terutama asam lemak omega-3), protein, vitamin E, vitamin C, seng.\n' , 'Buku Kebidanan' );");
        db6.execSQL("INSERT INTO melahirkan VALUES ('B002', 'Pijat Perineum', "+"'Pijat perineum selama kehamilan dapat membantu mempersiapkan perineum Anda untuk kelahiran sehingga risiko vagina robek dapat berkurang. Perineum sendiri adalah area di antara lubang vagina dan lubang anus Anda.\n\nPijat perineum juga dapat mencegah Anda dari episiotomi. Tidak hanya membantu soal fisik, pijat perineum selama kehamilan juga dapat meningkatkan kepercayaan wanita pada kemampuan tubuhnya untuk meregang dan melahirkan bayi.\n','Buku Kebidanan' );");
        db6.execSQL("INSERT INTO melahirkan VALUES ('B003', 'Perhatikan Posisi Anda Saat Melahirkan',"+"'Posisi Anda saat melahirkan mempunyai pengaruh yang cukup besar terhadap kemungkinan vagina robek. Berbaring dengan kaki diangkat atau posisi setengah berbaring dapat menempatkan tekanan ke tulang ekor dan perineum, sehingga dapat meningkatkan kemungkinan vagina robek.\n\nTemukanlah posisi ternyaman Anda saat melahirkan. Anda bebas bergerak selama persalinan untuk menemukan posisi terbaik Anda. Posisi yang disarankan untuk mengurangi kemungkinan vagina robek adalah dengan berbaring menghadap ke sisi kiri Anda.\n', 'Buku Kebidanan' );");
        db6.execSQL("INSERT INTO melahirkan VALUES ('B004', 'Atur Pernapasan Anda dan Ketahui Kapan Harus Mengejan',"+"'Sebelum mengejan untuk mendorong bayi Anda keluar, sebaiknya atur pernapasan Anda dengan baik. Tenang, ikuti naluri Anda untuk mengejan dan juga ikuti instruksi yang diberikan oleh dokter Anda. Ada waktunya kapan Anda harus mengejan dan juga kapan Anda harus menarik napas.\n\nMengejan saat tidak dibutuhkan hanya akan meningkatkan risiko Anda untuk mengalami vagina robek. Anda juga tidak perlu mengejan dengan kekuatan penuh seluruh tubuh Anda sambil menahan napas. Hal ini justru dapat mengurangi pasokan oksigen ke dalam tubuh Anda dan bayi.\n\nBuruknya, hal ini juga dapat menghambat aliran balik darah Anda sehingga menyebabkan pembengkakan. Anda mungkin menarik napas, kemudian mengejan sambil menahan napas. Namun untuk mencegah terjadinya robekan, sebaiknya Anda menghembuskan napas secara perlahan saat Anda mengejan.\n\nSaat kepala bayi sudah menyentuh vagina Anda, mungkin Anda akan merasakan sensasi menyengat dan tertekan. Namun, jangan terburu-buru ingin mengejan untuk mengeluarkan bayi Anda. Tunggu sampai perineum Anda benar-benar meregang sehingga sesuai dengan ukuran kepala bayi Anda. Jika dipaksakan di saat perineum Anda belum meregang sepenuhnya, maka vagina Anda mungkin akan robek.\n', 'Buku Kebidanan' );");
        db6.execSQL("INSERT INTO melahirkan VALUES ('B005', 'Gunakan Kompres Air Hangat',"+"'Saat bayi Anda sudah turun ke dasar panggul dan akan segera keluar, kompres air hangat mungkin membantu mengurangi kemungkinan vagina robek. Kehangatan dapat meningkatkan aliran darah ke daerah perineum dan membantu mengendurkan otot vagina Anda. Hal ini membantu Anda dalam mengurangi rasa sakit.\n', 'Buku Kebidanan' );");
    }

    public void generateData7(SQLiteDatabase db7) {
        db7.execSQL("INSERT INTO ibu VALUES ('C001', 'Mual Muntah',"+"'Dalam bahasa medis disebut emesis gravidarum atau morning sickness merupakan suatu keadaan mual yang terkadang disertai muntah (frekuensi kurang dari 5 kali) selama kehamilan, sebanyak 70–85% wanita mengalami mual muntah (Wegrzyniak, dkk, 2012).\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C002', 'Hipersalivasi', "+"' Air liur berlebih atau dalam bahasa medis disebut hipersalivas atau sialorrehea atau ptyalism adalah peningkatan sekresi air liur yang berlebihan (1–2 L/hari). Sebesar 2,4% wanita hamil pada trimester pertama mengalami peningkatan air liur (Freeman, 1994).\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C003', 'Pusing Trimester 1',"+"'biasanya terjadi pada awal kehamilan, penyebabnya pastinya belum diketahui, akan tetapi diduga oleh pengaruh hormon progestoren yang memicu dinding pembuluh darah melebar, sehingga mengakibatkan terjadinya penurunan tekanan darah dan membuat ibu merasa pusing.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C004', 'Mudah Lelah',"+"'Pada awal kehamilan, wanita sering mengeluhkan mudah lelah. Dalam teori yang muncul yaitu diakibatkan oleh penurunan dratis laju metabolisme dasar pada awal kehamilan, selain itu peningkatan progesteron memiliki efek menyebabkan tidur, dan keluhan ini akan hilang pada akhir trimester pertama.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C005', 'Heartburn Trimester 1',"+"'Wanita hamil sebesar 17–45% mengeluhkan rasa terbakar pada dada atau dalam medis disebut heartburn. Angka kejadian ini meningkat seiring dengan peningkatan usia kehamilan. Dalam penelitian di singapura ditemukan dari 22% pada trimester 1 menjadi 39% pada trimester 2 dan meningkat lagi menjadi 60% - 72% pada trimester 3.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C006', 'Peningkatan Frekuensi Berkemih',"+"'Lima puluh sembilan persen wanita mengalami peningkatan frekuensi berkemih pada trimester 1 kehamilan (Chalicha, 2002). Dan lebih dari 40% wanita hamil berkemih lebih dari 10 kali perhari pada siang hari, dan ikuti pula pada malam hari yaitu sebesar 72,9% dengan frekuensi lebih dari 4 kali (Sharma, 2009).\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C007', 'Konstipasi', "+"'Merupakan penurunan frekuensi buang air besar yang disertai dengan perubahan karakteristik feses yang menjadi keras sehingga sulit untuk dibuang atau dikeluarkan dan dapat menyebabkan kesakitan yang hebat pada penderitanya. Pada kehamilan, konstipasi terjadi pada 10% - 40% wanita (Vazquez, 2010). Dan pada TM I, konstipasi terjadi pada 24% wanita (Bradley, 2007).\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C008', 'Keluhan Psikologis Pada Trimester I',"+"'Selama kehamilan trimester I ibu dapat mengalami keluhan psikis yang positif dan negatif. Ibu yang merasa tidak sehat dan berharap untuk tidak hamil hampir 80% membenci kehamilannya. Banyak ibu yang merasa kecewa, menolak, cemasan dan sedihan.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C009', 'Pusing Trimester 2',"+"'Merupakan timbulnya perasaan melayang karena peningkatan volume plasma darah yang mengalami peningkatan hingga 50%. Peningkatan volume plasma akan meningkatkan sel darah merah sebesar 15-18%. Peningkatan sel darah merah akan mempengaruhi kadar haemoglobin darah, sehingga jika peningkatan volume dan sel darah merah tidak diimbangi dengan kadar haemaglobin yang cukup, akan menyebabkan terjadinya anemia.\n" + "Perubahan pada komposisi darah tubuh ibu hamil terjadi mulai minggu ke-24 kehamilan dan akan memuncak pada minggu ke-28 sampai ke-32, keadaan tersebut akan menetap pada minggu ke-36.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C011', 'Sering Berkemih',"+"'Seiring bertambahnya usia kehamilan, masa uterus akan bertambah dan ukuran uterus mengalami peningkatan, sehingga uterus membesar ke arah luar pintu atas panggul menuju rongga abdomen. Perubahan tersebut menyebabkan tertekannya kandungan kemih yang terletak tepat didepan uterus. Tertekannya kandung kemih oleh volume uterus yang semakin bertambah menyebabkan kapasitas kandung kemih berkurang, akibatnya daya kandung kemih berkurang. Hal tersebut memicu meningkatnya frekuensi kencing pada kehamilan trimester II.\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C012', 'Nyeri Perut Bawah', "+"'Nyeri perut bagian bawah biasa dikeluhkan 10%-30% ibu hamil pada akhir trismester I atau ketika memasuki trimester II. Keluhan ini biasanya terasa lebih pada ibu multigavida disebabkan karena tertariknya ligamentum, sehingga menimbulkan nyeri seperti kram ringan dan atau terasa seperti tusukan yang akan lebih terasa akibat gerakan tiba-tiba, dibagian perut bawah.\n" + "Nyeri perut bawah disebabkan oleh semakin membersarnya uterus sehingga keluar dari rongga panggul menuju rongga abdomen. Keadaan ini berakibat pada tertariknya ligamen-ligamen uterus seiring dengan pembesaran yang terjadi yang menimbulkan rasa tidaknyaman dibagian perut bawah.\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C013', 'Nyeri Punggung',"+"'nyeri pada bagian punggung atau low back pain dialami oleh 20%-25% ibu hamil. Keluhan ini dimulai pada usia kehamilan 12 minggu dan akan meningkat pada saat usia kehamilan 24 minggu hingga menjelang persalinan. Rasa nyeri sering dirasakan ibu pada waktu malam hari. Hal ini diakibatkan oleh pengaruh aliran darah vena kearah lumbal sebagai peralihan cairan dari intraseluler ke arah ekstraseluler akibat dari aktivitas yang dilakukan ibu (James et al, 2006).\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C014', 'Efek Kecoklatan Pada Wajah dan Sikatrik',"+"'Perubahan kulit yang terjadi selama kehamilan merupakan efek dari ketidakseimbangan hormon selama kehamilan, yang mempengaruhi perubahan pada kulit dan dialami oleh 90% wanita selama kehamilan.\n" + "Hal ini tidak menimbulkan rasa kurang nyaman ibu hamil, namun lebih menimbulkan efek yang berkenaan dengan estetika wanita, sehingga mempengaruhi psikologis seorang ibu. Keluhan yang sering dialami oleh wanita hamil yaitu timbulnya strecth mark dan hiperpigmentasi pada kulit.\n" + "Sikatrik atau streatch marck-striae merupakan garis terang atau gelap kemerahan yang biasa timbul pada bagian payudara, perut, bokong dan betis pada waktu kehamilan. Pada multigravida, striae kemerahan tersebut sering disertai garis-garis putih semu keperekaan yang mencerminkan striae lama (pada kehamilan sebelumnya). Strecth mark atau striae gravidarum diakibatkan oleh hiperdistensi yang terjadi pada jaringan kulit akibat peningkatan ukuran maternal yang menyebabkan peregangan pada lapisan kolagen kulit, terutama pada payudara, abdomen dan paha. Etiologi daru strecth marks diduga akibat pengaruh hormon esterogen, adrenocorticoid, dan relaxin yang mengubah kolagen dan elastisitas jaringan. (Hellen dkk, 2008).\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C015', 'Sekret Vagina Berlebih',"+"'Leukorhea merupakan pengeluaran yang dihasilkan oleh serviks maupun vagina, yang berasal dari metabolisme glikogen dan dikeluarkan dalam bentuk lendir maupun semi cair. Leukorhea biasa terjadi pada wanita yang mendekati masa ovulasi dan pada masa kehamilan yaitu pada awal kehamilan, serta secara berangsur-angsur akan meningkat hingga pertengahan timester III.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C016', 'Konstipasi',"+"'Sembelit atau konstipasi adalah suatu keadaan dimana sekresi dari sisa metabolisme nutrisi tubuh bentuk feces mengalami gangguan yang menyebabkan feces menjadi keras dan menimbulkan kesulitan saat defekasi.\n" + "Trottier tahun 2012 menyebutkan bahwa angka kejadian sembelit pada ibu hamil berkisar antara 11-38%, yang diakibatkan karena penurunan dari peristaltik usus akibat dari peningkatan hormon progestoren. Studi yang dilakukan oleh bradley tahun 2007 mendapatkan hasil bahwa konstipasi terjadi pada trimester I sebanyak 24%, 26% pada trimester II dan 24% pada trimester III, serta kejadiannya meningkat  4 kali pada ibu dengan riwayat konstipasi.\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C017', 'Penambahan Berat Badan', "+"'Penambahan berat badan merupakan suatu  hal yang menjadi bagian pada proses kehamilan, dimana hal ini menggambarkan keadaan suatu kehamilan seseorang. Penambahan berat pada kehamilan harus dipantau dengan baik, hal ini menjadi salah satu indikator keadaan kehamilan.\n" + "Berat badan mengalami penambahan secara signifikan dapat menjadi tanda terjadinya gangguan gestasional (preeklamsia). Sedangkan ibu dengan berat badan yang tidak mengalami peningkatan selama kehamilan dapat menjadi faktor penyebab terjadinya pertumbuhan janin terhambat akibat gangguan pada ibu. Gangguan tersebut dapat dikarenakan penyakit yang menyertai ibu sebelum kehamilan. (James dkk, 2006).\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C018', 'Pergerakan Janin',"+"'Pergerakan janin atau quickening yaitu keadaan dimana ibu merasakan gerakan janin pertama kali pada masa kehamilannya. Seorang multigravida, biasanya mulai merasakan pergerakan janin pertama kali pada usia 16–18 minggu, sedangkan pada primigravida pergerakan mulai dirasakan pada minggu ke–18 – 20. Beberapa studi menyatakan bahwa sebagian ibu merasakan pergerakan janin setelah 20 minggu usia kehamilannya atau lebih.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C019', 'Perubahan Psikologis Trimester II',"+"'Perubahan psikologis yang terjadi tidak lepas dari pengaruh keseimbangan hormonal serta kemampuan ibu mengatasi ketidaknyaman akibat perubahan fisologi yang terjadi sejak awal kehamilan. Pada trimester II perubahan psikologis sangat dipengaruhi oleh kemampuan ibu mengatasi ketidaknyamanan yang terjadi pada trimester 1 serta penerimaan ibu terhadap kehamilannya. Perubahan psikologis pada trimester II merupakan suatu kelanjutan dari kemampuan ibu mengatasi perubahan yang terjadi (kopping stress) pada trimester I Jika seorang wanita selama kehamilan trimester I tidak dapat mengatasi perubahan yang terjadi dengan baik maka kesulitan tersebut akan semakin besar pada trimester II. studi yang dilakukan oleh Catano, dkk(2004) menunjukkan bahwa perubahan tubuh yang mulai terjadi pada trimester II akan menjadikan ibu mengalami krisis kepercayaan diri yang dikenal dengan krisis body image.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C020', 'Sering Terjadi Kontraksi Palsu',"+"'Seiring pertumbuhan janin dalam perut ibu yang mulai mendapatkan asupan nutrisi, selain tubuhnya yang kini mulai tumbuh sempurna, gerakannya pun juga akan terasa lebih jelas. Sensasi ini sering disertai dengan membuat tubuh terasa tidak nyaman, salah satunya yang mungkin akan sering dirasakan ialah kontraksi Braxton Hicks atau lebih sering disebut dengan kontraksi palsu.\n" + "Kontraksi ini berbeda dengan kontraksi yang dirasakan sebelum melahirkan, biasanya kontraksi dirasakan lebih ringan dan akan hilang dengan sendirinya. Jika calon ibu sering merasakan kontraksi ringan ini mungkin memang akan meninggalkan rasa was – was dan sedikit sesak di perut. Namun tidak perlu terlalu dikhawatirkan secara berlebihan karena kontraksi ini biasanya akan hilang sendirinya. Dan kondisi ini akan lebih sering terjadi jika calon ibu melakukan aktifittas yang cukup melelahkan baik di siang atau pun malam hari. Untuk itu cukup istirahat.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C021', 'Sakit Punggung',"+"'Perut yang mulai semakin membesar karena pertumbuhan janin dalam rahim bisa membuat  postur tubuh calon ibu berubah. Dan hormon relaxin atau hormon kehamilan akan membuat tulang panggul sedikit merenggang, hal ini terjadi untuk mengantisipasi kelahiran dan membuka jalan lahir nantinya. Namun hal ini bisa saja memberikan efek negatif pada bagian tubuh yang lain terutama bagian punggung. Selain itu beban tubuh di bagian depan yang bertambah juga membuat punggung harus menjadi tumpuan berat yang memperparah kondisi sakit tersebut.\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C022', 'Sesak Napas', "+"'Dalam trimester ketiga ini janin di dalam rahim akan tumbuh dengan pesat, setiap bagian dari organnya akan tumbuh dan matang agar ketika tiba waktunya untuk lahir maka bayi akan siap dilahirkan. Dan karena perkembangannya ini, satu keluhan yang mungkin akan sering dirasakan ialah mudah sesak napas. Hal ini terjadi karena janin yang tumbuh akan menyita seluruh ruang di perut sang ibu dan hal ini akan membuat ibu akan merasa mudah sesak napas.\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C023', 'Heartburn Trimester 3',"+"'Kebanyakan wanita hamil akan merasakan heartburn, atau rasa panas yang terasa di bagian dada seperti perasaan terbakar yang diakibatkan oleh asam lambung yang naik hingga ke bagian kerongkongan. Hal ini terjadi akibat pengaruh dari hormon kehamilan, dan juga pertumbuhan janin yang menekan rongga perut hingga membuat cairan asam naik.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C024', 'Muncul Spider veins dan juga varises',"+"'Peningkatan sirkulasi darah dalam tubuh selama kehamilan bisa menyebabkan pembuluh darah merah naik yang berwana biru atau merah, yang dikenal sebagai spider veins muncul di berbagai titik di tubuh. Seperti di bagian wajah, leher dan juga lengan, selain itu pembuluh darah ini juga akan semakin terlihat di bagian kaki, yang sering disebut varises. Hal ini memang cukup sulit dihindari, apalagi bila ibu hamil malas bergerak. Varises terjadi ketika katup di dalam pembuluh darah di kaki menjadi lembut atau lemah, yang memungkinkan darah mengalir ke bagian belakang dan membentuk tonjolan yang menyakitkan. Namun kondisi ini bisa dikurangi salah satunya dengan cara olah raga teratur dan sering mengangkat kaki ke atas. Dan perbanyak melakukan gerakan ringan demi mengurangi rasa sakit yang timbul karena varises ini bisa saja cukup mengganggu.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C025', 'Sembelit atau Masalah Pencernaan',"+"'Hal yang sering dirasakan oleh ibu hamil di akhir trimester yang sering kali mengganggu ialah sembelit atau susah buang air besar. hal ini terjadi lagi – lagi karena perubahan hormon di dalam tubuh, yang berpengaruh pada fungsi usus yang menjadi lebih lambat saat mencerna makanan. Hal ini bisa diatasi dengan perbanyak minum air putih dan juga mengkonsumsi makanan yang kaya akan serat dan juga vitamin. Bukan cuma suplemen vitamin saja tetapi juga sayur – sayuran organik yang sehat bagi tubuh. Dan jika masih terasa sulit buang air besar, juga bisa menggunakan obat pencahar yang khusus untuk ibu hamil yang bisa didapat di apotek sesuai dengan resep dokter.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C026', 'Sering Buang Air Kecil',"+"'Saat trimester terakhir kehamilan, biasanya janin akan mulai bergerak turun ke arah panggul untuk mencari jalan lahir. Dan karenanya mungkin akan membuat kandung kemih terasa ada tekanan yang lebih dan hal inilah yang akan membuat ibu hamil menjadi lebih sering buang air kecil. Tekanan ekstra ini pun juga bisa membuat ibu hamil ngompol tanpa sengaja, terlebih lagi ketika tertawa, batuk atau pun bersin. Jika hal ini menimbulkan ketidak nyamanan, pertimbangkan untuk menggunakan panti liner. Namun jika cairan yang keluar bukanlah air seni, maka patut diwaspadai dan segera hubungi rumah sakit atau klinik terdekat untuk mendapat perawatan lebih lanjut.\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C027', 'Edema atau Kaki Bengkak', "+"'Edema atau bengkak pada kaki selama kehamilan bisa saja menjadi tanda serius yang harus diwaspadai. Karena hal ini terjadi disebabkan oleh retensi cairan di bagian bawah tubuh yang terjadi karena ibu hamil terlalu banyak beraktifitas. Meskipun bengkak atau edema bisa saja mereda, namun pada sebagian orang hal ini tidak bisa begitu saja hilang dengan sendirinya.\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C028', 'Menjadi Lebih Emosional',"+"'Seiring berkembangnya janin dalam tubuh, kekhawatiran tentang persalinan bisa saja muncul dan mengganggu pikiran. Jika hal ini dibiarkan maka bisa mengganggu perkembangan emosi janin yang dikandung, karena emosi sang ibu pun bisa dirasakan oleh sang calon bayi. Untuk itu pertimbangkan untuk mengikuti senam kehamilan, karena selain mendapatkan latihan untuk menjaga kehamilan. Ibu hamil juga akan dibekali wawasan yang cukup untuk menghadapi kehamilan serta persalinan sehingga bisa lebih kuat secara emosi.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C029', 'Insomnia',"+"'Karena pengaruh hormon yang naik turun dan kekhawatiran berlebihan akan proses kelahiran biasanya ibu hamil menjadi sulit tidur atau insomnia. Keadaan ini tentu kurang baik untuk kesehatan ibu dan juga janin yang dalam tahap pematangan organ tubuhnya. Sulit tidur juga membuat emosi ibu hamil meningkat dengan signifikan dan mudah marah sehingga hal ini kurang baik bagi janin dalam kandungannya.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C030', 'Tekanan Darah Tinggi',"+"'Hal yang juga sering dikeluhkan saat usia kehamilan memasuki trimester ketiga ialah tekanan darah tinggi. Kondisi ini umum terjadi pada semua ibu hamil karena lagi – lagi pengaruh hormon kehamilan. Namun kondisi hipertensi atau tekanan darah tinggi ini patut diwaspadai jika tekanan darah ibu hamil lebih dari 140/90 mmHg. Karena bisa menyebabkan kondisi preklamsia atau keracunan kehamilan yang sangat berbahaya bagi ibu bahkan janin.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C031', 'Kelebihan Berat Badan',"+"'Pertumbuhan janin dalam rahim ibu dari awal kehamilan hingga trimester ketiga tentu akan membuat tubuh ibu berubah drastis. Salah satunya berat badan ibu yang akan meningkat secara signifikan. Ada ibu yang pertambahan berat badannya sedikit dan ada pula yang melonjak begitu tinggi, hal ini tentu harus diwaspadai selain menyebabkan ibu jadi kesulitan untuk bergerak dan ber-aktifitas. Kelebihan berat badan bisa mengindikasikan bahwa ibu hamil mengalami diabetes kehamilan. Dan hal ini bisa menyebabkan bayi lahir besar yang bisa menyulitkan untuk terjadi kelahiran normal.\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C032', 'Meningkatnya Kadar Gula Darah', "+"'Di saat hamil, kecukupan nutrisi haruslah terpenuhi dengan maksimal agar tumbuh kembang janin tidak terganggu. Namun terkadang beberapa kondisi membuat seorang ibu hamil yang memang sudah memiliki riwayat diabetes justru membuat kadar gulanya mengalami peningkatan. Tak lain karena makanan yang dikonsumsi yang memang berlebihan, karenanya penting untuk selalu menjaga asupan nutrisi selama kehamilan tetap seimbang. Sebab diabetes selama kehamilan tak hanya berbahaya untuk janin tetapi juga calon ibu.\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C033', 'Mulas',"+"'Mulas mungkin akan lebih sering dirasakan ketika kehamilan memasuki tahap akhir trimester. Kondisi ini karena ukuran janin yang mulai membesar dan membutuhkan ruang yang cukup banyak dalam rongga perut ibu. Keadaan ini harus dibedakan dengan rasa mulas akibat kontraksi palsu ataupun kontraksi sebenarnya. Biasanya ibu hamil akan mudah mulas jika mengkonsumsi makanan yang memiliki rasa yang kuat seperti makanan pedas.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C034', 'Morning Sickness',"+"'Sebagian wanita hamil akan mengalami yang namanya morning sickness dan akan menghilang seiring dengan bertambahnya usia kehamilan. Namun pada beberapa wanita, kondisi ini bisa bertahan hingga kelahiran bayi. Hal ini memang dipengaruhi oleh hormon kehamilan setiap wanita yang berbeda, sehingga bisa sangat mengganggu tahapan kehamilan yang dilalui. Periksakan ke dokter kandungan atau bidan terdekat untuk mengkonsultasikan kondisi ini. Sebab bila dibiarkan bia membuat ibu hamil kekurangan nutrisi yang penting dalam tahap perkembangan janin.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C035', 'Mudah Lelah',"+"'Kondisi perut yang mulai membesar di akhir trimester ketiga tentu memberikan beban yang cukup berat pada tubuh. Sehingga ibu hamil akan mudah sekali lelah. Usahakan untuk selalu beristirahat dengan cukup setiap kali ada waktu. Dan hindari untuk memakai sepatu berhak tinggi, selain berbahaya ibu hamil tentu akan sangat mudah lelah.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C036', 'Pusing Trimester 3',"+"'Tak hanya mudah lelah, keluhan yang sering dirasakan ibu hamil di tahap akhir kehamilannya ini ialah mudah pusing. Hal ini dipicu karena tekanan darah yang cukup tinggi karena pengaruh hormon kehamilan. Hal ini tidaklah berbahaya sehingga tidak perlu mengkonsumsi obat – obatan untuk mengurangi keluhan tersebut. Lebih baik istirahat yang cukup, dan apabila sedang berbaring jangan merubah dengan cepat karena bisa membuat kepala terasa semakin pusing. Meminum teh herbal dengan aroma yang menyegarkan seperti chamomile maupun teh melati bisa mengurangi sedikit pusing yang dirasakan.\n' , 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C037', 'Sakit Pinggang', "+"'Beban berat disebabkan janin yang tumbuh dalam rahim juga dapat menimbulkan rasa sakit di pinggang. Keluhan ini akan semakin meningkat seiring usia kehamilan dan biasanya akan menghilang setelah melahirkan. Untuk mengatasinya banyak – banyak olah raga dengan mengikuti kelas senam kehamilan misalnya. Di dalamnya setiap ibu hamil akan diajari untuk melakukan gerakan yang bisa mengurangi rasa sakit tersebut. Atau pun bisa meminta pasangan untuk memberikan pijatan lembut agar nyerinya berkurang.\n','Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C038', 'Nyeri di Payudara',"+"'Keluhan yang juga akan cukup membuat ibu hamil sedikit terganggu ada di bagian payudara. Sebab payudara mulai menghasilkan air susu yang nantinya akan menyuplai nutrisi bagi bayi, sehingga terkadang rasa nyeri sedikit mengganggu. Untuk mengatasinya lakukan pemijatan sendiri dengan menggunakan handuk hangat untuk mengurangi rasa nyeri yang mengganggu dan mempersiapkan ASI agar nantinya bisa lancar keluar segera setelah bayi lahir.\n', 'Buku Kebidanan' );");
        db7.execSQL("INSERT INTO ibu VALUES ('C039', 'Stretch Mark',"+"'Satu lagi keluhan yang pastinya cukup mengganggu di trimester ketiga yaitu stretch mark atau guratan yang terlihat di perut. Ini terjadi karena perut yang membesar selama kehamilan tentu membuat bagian tubuh terutama kulit di sekitar perut merenggang sehingga meninggalkan bekas yang membuat kulit tampak buruk. Sebetulnya cara mengatasinya mudah saja. Sebab ketika kulit merenggang pasti akan terasa gatal, nah karenanya jangan menggaruknya karena dapat menimbulkan bekas guratan yang sering disebut stretch mark. Selain itu bisa menggunakan lotion untuk memberikan kelembaban agar tida mudah terjadi stretch mark.\n', 'Buku Kebidanan' );");
    }

    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    }

    public void onCreate(SQLiteDatabase db) {
    }
}


